

DICT_BULKS=[

    #https://www.fec.gov/data/browse-data/?tab=bulk-data

    #1
    {
    "folder": "all_candidates", 
    "url_suffix": "weball",
    "colnames": [
        "CAND_ID",
        "CAND_NAME",
        "CAND_ICI",
        "PTY_CD",
        "CAND_PTY_AFFILIATION",
        "TTL_RECEIPTS",
        "TRANS_FROM_AUTH",
        "TTL_DISB",
        "TRANS_TO_AUTH",
        "COH_BOP",
        "COH_COP",
        "CAND_CONTRIB",
        "CAND_LOANS",
        "OTHER_LOANS",
        "CAND_LOAN_REPAY",
        "OTHER_LOAN_REPAY",
        "DEBTS_OWED_BY",
        "TTL_INDIV_CONTRIB",
        "CAND_OFFICE_ST",
        "CAND_OFFICE_DISTRICT",
        "SPEC_ELECTION",
        "PRIM_ELECTION",
        "RUN_ELECTION",
        "GEN_ELECTION",
        "GEN_ELECTION_PRECENT",
        "OTHER_POL_CMTE_CONTRIB",
        "POL_PTY_CONTRIB",
        "CVG_END_DT",
        "INDIV_REFUNDS",
        "CMTE_REFUNDS",
        ],
    },

    #2
    {
    "folder": "candidate_master",
    "url_suffix": "cn",
    "colnames": [
        "CAND_ID",
        "CAND_NAME",
        "CAND_PTY_AFFILIATION",
        "CAND_ELECTION_YR",
        "CAND_OFFICE_ST",
        "CAND_OFFICE",
        "CAND_OFFICE_DISTRICT",
        "CAND_ICI",
        "CAND_STATUS",
        "CAND_PCC",
        "CAND_ST1",
        "CAND_ST2",
        "CAND_CITY",
        "CAND_ST",
        "CAND_ZIP",
        ],
    },

    #3
    {
    "folder": "candidate_committee_linkages",
    "url_suffix": "ccl",
    "colnames": [
        "CAND_ID",
        "CAND_ELECTION_YR",
        "FEC_ELECTION_YR",
        "CMTE_ID",
        "CMTE_TP",
        "CMTE_DSGN",
        "LINKAGE_ID",
        ],
    },

    #4
    {
    "folder": "house_senate_current_campaigns",
    "url_suffix": "webl",
    "colnames": [
        "CAND_ID",
        "CAND_NAME",
        "CAND_ICI",
        "PTY_CD",
        "CAND_PTY_AFFILIATION",
        "TTL_RECEIPTS",
        "TRANS_FROM_AUTH",
        "TTL_DISB",
        "TRANS_TO_AUTH",
        "COH_BOP",
        "COH_COP",
        "CAND_CONTRIB",
        "CAND_LOANS",
        "OTHER_LOANS",
        "CAND_LOAN_REPAY",
        "OTHER_LOAN_REPAY",
        "DEBTS_OWED_BY",
        "TTL_INDIV_CONTRIB",
        "CAND_OFFICE_ST",
        "CAND_OFFICE_DISTRICT",
        "SPEC_ELECTION",
        "PRIM_ELECTION",
        "RUN_ELECTION",
        "GEN_ELECTION",
        "GEN_ELECTION_PRECENT",
        "OTHER_POL_CMTE_CONTRIB",
        "POL_PTY_CONTRIB",
        "CVG_END_DT",
        "INDIV_REFUNDS",
        "CMTE_REFUNDS", 
        ],
    },

    #5
    {
    "folder": "committee_master",
    "url_suffix": "cm",
    "colnames": [
        "CMTE_ID",
        "CMTE_NM",
        "TRES_NM",
        "CMTE_ST1",
        "CMTE_ST2",
        "CMTE_CITY",
        "CMTE_ST",
        "CMTE_ZIP",
        "CMTE_DSGN",
        "CMTE_TP",
        "CMTE_PTY_AFFILIATION",
        "CMTE_FILING_FREQ",
        "ORG_TP",
        "CONNECTED_ORG_NM",
        "CAND_ID",
        ],
    },

    #6
    {
    "folder": "pac_summary",
    "url_suffix": "webk",
    "colnames": [
        "CAND_ID",
        "CMTE_NM",
        "CMTE_TP",
        "CMTE_DSGN",
        "CMTE_FILING_FREQ",
        "TTL_RECEIPTS",
        "TRANS_FROM_AFF",
        "INDV_CONTRIB",
        "OTHER_POL_CMTE_CONTRIB",
        "CAND_CONTRIB",
        "CAND_LOANS",
        "TTL_LOANS_RECEIVED",
        "TTL_DISB",
        "TRANF_TO_AFF",
        "INDV_REFUNDS",
        "OTHER_POL_CMTE_REFUNDS",
        "CAND_LOAN_REPAY",
        "LOAN_REPAY",
        "COH_BOP",
        "COH_COP",
        "DEBTS_OWED_BY",
        "NONFED_TRANS_RECEIVED",
        "CONTRIB_TO_OTHER_CMTE",
        "IND_EXP",
        "PTY_COORD_EXP",
        "NONFED_SHARE_EXP",
        "CVG_END_DT",    
        ],
    },

    #7
    {
    "folder": "contributions_by_individuals",
    "url_suffix": "indiv",
    "colnames": [
        "CMTE_ID",
        "AMNDT_IND",
        "RPT_TP",
        "TRANSACTION_PGI",
        "IMAGE_NUM",
        "TRANSACTION_TP",
        "ENTITY_TP",
        "NAME",
        "CITY",
        "STATE",
        "ZIP_CODE",
        "EMPLOYER",
        "OCCUPATION",
        "TRANSACTION_DT",
        "TRANSACTION_AMT",
        "OTHER_ID",
        "TRAN_ID",
        "FILE_NUM",
        "MEMO_CD",
        "MEMO_TEXT",
        "SUB_ID",
        ],
    },

    #8
    {
    "folder": "contributions_from_committees_to_candidates",
    "url_suffix": "pas2",
    "colnames": [
        "CMTE_ID",
        "AMNDT_IND",
        "RPT_TP",
        "TRANSACTION_PGI",
        "IMAGE_NUM",
        "TRANSACTION_TP",
        "ENTITY_TP",
        "NAME",
        "CITY",
        "STATE",
        "ZIP_CODE",
        "EMPLOYER",
        "OCCUPATION",
        "TRANSACTION_DT",
        "TRANSACTION_AMT",
        "OTHER_ID",
        "CAND_ID",
        "TRAN_ID",
        "FILE_NUM",
        "MEMO_CD",
        "MEMO_TEXT",
        "SUB_ID",
        ],
    },

    #9
    {
    "folder": "any_transaction_from_one_committee_to_another",
    "url_suffix": "oth",
    "colnames": [
        "CMTE_ID",
        "AMNDT_IND",
        "RPT_TP",
        "TRANSACTION_PGI",
        "IMAGE_NUM",
        "TRANSACTION_TP",
        "ENTITY_TP",
        "NAME",
        "CITY",
        "STATE",
        "ZIP_CODE",
        "EMPLOYER",
        "OCCUPATION",
        "TRANSACTION_DT",
        "TRANSACTION_AMT",
        "OTHER_ID",
        "TRAN_ID",
        "FILE_NUM",
        "MEMO_CD",
        "MEMO_TEXT",
        "SUB_ID",
        ],
    },

    #10
    {
    "folder": "operating_expenditures",
    "url_suffix": "oppexp",
    "colnames": [
        "CMTE_ID",
        "AMNDT_IND",
        "RPT_YR",
        "RPT_TP",
        "IMAGE_NUM",
        "LINE_NUM",
        "FORM_TP_CD",
        "SCHED_TP_CD",
        "NAME",
        "CITY",
        "STATE",
        "ZIP_CODE",
        "TRANSACTION_DT",
        "TRANSACTION_AMT",
        "TRANSACTION_PGI",
        "PURPOSE",
        "CATEGORY",
        "CATEGORY_DESC",
        "MEMO_CD",
        "MEMO_TEXT",
        "ENTITY_TP",
        "SUB_ID",
        "FILE_NUM",
        "TRAN_ID",
        "BACK_REF_TRAN_ID",
        ],
    }
]